name: mops test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install moc
        run: npx mocv use latest

      - name: install mops
        run: npm i ic-mops -g

      - name: install mops packages
        run: mops install

      - name: run integration tests
        run: ./scripts/test_canister.sh
