name: ic-websocket-cdk-mo tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: aviate-labs/setup-dfx@v0.2.6
        with:
          dfx-version: 0.14.1

      - name: install mops
        run: npm i ic-mops -g

      # the following steps are replicated in the scripts/test_canister.sh file
      - name: Install dependencies for integration tests
        run: |
          cd tests
          mops install
          npm install

      - name: Prepare environment for integration tests
        run: |
          cd tests
          dfx start --clean --background
          npm run deploy:tests
          npm run generate
          echo "CANISTER_ID_TEST_CANISTER='$(npx json -f .dfx/local/canister_ids.json test_canister.local)'" > .env

      - name: Run integration tests
        run: cd tests && npm run test:integration
